# Generated by Django 4.2.2 on 2023-06-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
