# Generated by Django 4.2.2 on 2023-06-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='clipping.tag', verbose_name='tags'),
        ),
    ]
