# Generated by Django 4.2.2 on 2023-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
