# Generated by Django 4.2.2 on 2023-06-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0002_alter_clipping_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='source',
            field=models.URLField(verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
