# Generated by Django 4.2.2 on 2023-06-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0004_alter_clipping_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='clipping.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
