# Generated by Django 4.2.2 on 2023-06-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ID de Telegram'),
        ),
    ]
